service: jeffpay-alt
provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  timeout: 30
  logs:
    restApi: true
  environment:
    TZ: Asia/Tokyo
    USER_TABLE:
      Ref: UserTable
    PAYMENT_HISTORY_TABLE:
      Ref: PaymentHistoryTable
    NOTIFICATION_QUEUE:
      Fn::GetAtt:
        - NotificationQueue
        - Arn
    NOTIFICATION_ENDPOINT: 'https://o5wb09mgpg.execute-api.ap-northeast-1.amazonaws.com/prod/notification'
    LOCATION_ENDPOINT: 'https://o5wb09mgpg.execute-api.ap-northeast-1.amazonaws.com/prod/location'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "*"

functions:
  CreateUser:
    handler: handler.user_create
    events:
      - http:
          path: users
          method: post
  WalletCharge:
    handler: handler.wallet_charge
    events:
      - http:
          path: wallet/charge
          method: post
  WalletUse:
    handler: handler.wallet_use
    events:
      - http:
          path: wallet/use
          method: post
  WalletTransfer:
    handler: handler.wallet_transfer
    events:
      - http:
          path: wallet/transfer
          method: post
  GetUserSummary:
    handler: handler.get_user_summary
    events:
      - http:
          path: users/{userId}/summary
          method: get
  GetPaymentHistory:
    handler: handler.get_payment_history
    events:
      - http:
          path: users/{userId}/history
          method: get
  SendNotification:
    handler: handler.send_notification
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotificationQueue
              - Arn

resources:
  Resources:
    NotificationQueue:
      Type: AWS::SQS::Queue
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    PaymentHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: transactionId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: transactionId
            KeyType: RANGE
        LocalSecondaryIndexes: 
        - IndexName: "timestampIndex"
          KeySchema: 
            - AttributeName: "userId"
              KeyType: "HASH"
            - AttributeName: "timestamp"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "KEYS_ONLY"
